### ISSUE TITLE
Loaded item definition is unnecessary

### ISSUE THREAD

**Issue by stujones11** [BrunoMine/musket#2]
I noticed that you are overriding the built-in 'loaded' item definition, this may have been due to a bug in the shooter api which is now fixed.

Unless there was some other reason to do this you can safely remove the following lines and set `rounds` to just 1 instead of 1.1
https://github.com/BrunoMine/musket/blob/19112b52bee1afdff85adc71ba062596e5375d79/init.lua#L66-L94
I also notice you have the `step` equal to `range `which makes the hit time almost instant, I am not sure if that was intended but you may consider reducing the step to 10 or 15 for better realism.

**Comment by BrunoMine** [comment]
> I noticed that you are overriding the built-in 'loaded' item definition, this may have been due to a bug in the shooter api which is now fixed.

Is there any other way to do the replacement after the shot? (like after_shot or on_shot callbacks)

**Comment by BrunoMine** [comment]
> I also notice you have the `step` equal to `range `which makes the hit time almost instant, I am not sure if that was intended but you may consider reducing the step to 10 or 15 for better realism.

In my tests, this prevented the node from being removed with the projectile. (and I want it removed)

**Comment by stujones11** [comment]
> Is there any other way to do the replacement after the shot?

I am not sure what you mean here? AFAIK, it _is_ replaced after the shot.

> In my tests, this prevented the node from being removed with the projectile. (and I want it removed)

Have you tried it with the latest version of shooter? I am pretty sure it was removing the nodes it was capable of in my own tests.

**Comment by BrunoMine** [comment]
> I am not sure what you mean here? AFAIK, it _is_ replaced after the shot.
This last version of shooter mod has fixed it, now it work fine.

> Have you tried it with the latest version of shooter? I am pretty sure it was removing the nodes it was capable of in my own tests.

**Comment by BrunoMine** [comment]
Okay, now it works fine. Thank you.

**Comment by BrunoMine** [comment]
Updated. [commit](https://github.com/BrunoMine/musket/commit/121f2cafa47d7bb95ef430a417e682d808cf0fad)

**Comment by stujones11** [comment]
Please see my comment on the commit :)

https://github.com/BrunoMine/musket/commit/121f2cafa47d7bb95ef430a417e682d808cf0fad#commitcomment-33008974
